### ISSUE TITLE
Abstraction and standardisation of environment variables

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/Full-Stack-Docker-Tazama#79]
EPIC https://github.com/tazama-lf/frms-coe-lib/issues/186

https://github.com/tazama-lf/docs/blob/dev/Research-Articles/Encapsulation-of-environment-variables.md

## Acceptance criteria

 - Updated .env files

**Comment by Justus-at-Tazama** [comment]
[rulexxx.zip](https://github.com/user-attachments/files/17367958/rulexxx.zip)
